### ISSUE TITLE
Add Readme file to your folder

### ISSUE THREAD

**Issue by oladhari** [kinopppp/my_web_site001#3]
please add a readme file to your project with details of :

- [ ] used technologies
- [ ] purpose of the project
- [ ] link to the hosted web page of this folder

[here](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) a template of Readme file

**Comment by kinopppp** [comment]
I made readme file.
please check it.
[Readme.md](https://github.com/kinopppp/my_web_site001/blob/master/README.md)

**Comment by kinopppp** [comment]
i made readme file.
please check it from the link below.

https://github.com/kinopppp/my_web_site001/blob/master/README.md

**Comment by oladhari** [comment]
@kinopppp 
thank you but I do not see any related PR, you made it through the GitHub website?

**Comment by kinopppp** [comment]
@oladhari 
sorry for late reply.
i made through github page.
